[programs.devnet]
myepicproject = "DBzaZUUKvdTADrpuhNX2MmSp8BzSZZ6kEp3E5FjVFhDV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/nestoredduardo/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 

[test]
startup_wait = 100000
